/*
 * Copyright 2024 the original author or authors.
 *
 * All rights reserved. This program and the accompanying materials are
 * made available under the terms of the Eclipse Public License v2.0 which
 * accompanies this distribution and is available at
 *
 * https://www.eclipse.org/legal/epl-v20.html
 */
package org.lazyparams.showcase;

import org.junit.Rule;
import org.junit.Test;
import org.lazyparams.VerifyJupiterRule;

/**
 * @author Henrik Kaipe
 */
public class ToListDefaultPairwiseTest {

    @Rule
    public VerifyJupiterRule expect = new VerifyJupiterRule(ToListDefaultPairwise.class) {

        String evaluateDigitPrefix(String nameRgx) {
            char firstCh = nameRgx.charAt(0);

            if (firstCh < '0' || '9' < firstCh) {
                return nameRgx;
            } else {
                StringBuilder sb = new StringBuilder(" src-size=").append(firstCh);
                if (2 <= nameRgx.length()) {
                    sb.append(" / 0\\.\\d\\d\\ds").append(nameRgx.substring(1));
                }
                return sb.toString();
            }
        }

        @Override
        public VerifyJupiterRule.SpecifyFailMessageOrNextResult fail(String nameRgx) {
            return super.fail(evaluateDigitPrefix(nameRgx));
        }
        @Override
        public VerifyJupiterRule.NextResult pass(String nameRgx) {
            return super.pass(evaluateDigitPrefix(nameRgx));
        }
    };

    @Test
    public void intuitiveSeedsOnOneOrTwo() {
        expect
                .fail(" src-size=0 / 0\\.\\d{3}s")
                .pass("ToListDefaultPairwise src-size=0",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=0")
                .pass("1 = \\[0\\]")
                .pass("ToListDefaultPairwise src-size=1",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=1")
                .pass("2 = 0,0 \\[0\\]")
                .pass("2 = 1,0 \\[0, 1\\]")
                .pass("2 = 2,0 \\[1\\]")
                .pass("2")
                .pass("ToListDefaultPairwise src-size=2",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=2")
                .pass("3 = 0,0 \\[0\\]")
                .pass("3 = 1,1 \\[1\\]")
                .pass("3 = 2,0 \\[0, 2\\]")
                .pass("3 = 0,1 \\[0, 1\\]")
                .pass("3 = 1,0 \\[1, 2\\]")
                .pass("3 = 2,1 \\[2\\]")
                .pass("3")
                .pass("ToListDefaultPairwise src-size=3",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=3")
                .pass("4 = 0,0 \\[0\\]")
                .pass("4 = 1,1 \\[1, 3\\]")
                .pass("4 = 2,0 \\[0, 2\\]")
                .pass("4 = 3,1 \\[3\\]")
                .pass("4 = 4,0 \\[2\\]")
                .pass("4 = 0,1 \\[0, 3\\]")
                .pass("4 = 1,0 \\[0, 1\\]")
                .pass("4 = 2,1 \\[1, 2\\]")
                .pass("4 = 3,0 \\[2, 3\\]")
                .pass("4 = 4,1 \\[1\\]")
                .pass("4")
                .pass("ToListDefaultPairwise src-size=4",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=4")
                .pass("5 = 0,0 \\[0\\]")
                .pass("5 = 1,1 \\[1, 4\\]")
                .pass("5 = 2,2 \\[2\\]")
                .pass("5 = 3,0 \\[0, 3\\]")
                .pass("5 = 4,1 \\[4\\]")
                .pass("5 = 0,2 \\[0, 2\\]")
                .pass("5 = 1,0 \\[0, 1\\]")
                .pass("5 = 2,1 \\[1, 2\\]")
                .pass("5 = 3,2 \\[3\\]")
                .pass("5 = 4,0 \\[3, 4\\]")
                .pass("5 = 0,1 \\[0, 4\\]")
                .pass("5 = 1,2 \\[1\\]")
                .pass("5 = 2,0 \\[2, 3\\]")
                .pass("5 = 3,1 \\[1, 3\\]")
                .pass("5 = 4,2 \\[2, 4\\]")
                .pass("5")
                .pass("ToListDefaultPairwise src-size=5",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=5")
                .pass("6 = 0,0 \\[0\\]")
                .pass("6 = 1,1 \\[1\\]")
                .pass("6 = 2,2 \\[2, 5\\]")
                .pass("6 = 3,0 \\[0, 3\\]")
                .pass("6 = 4,1 \\[1, 4\\]")
                .pass("6 = 5,2 \\[5\\]")
                .pass("6 = 6,0 \\[3\\]")
                .pass("6 = 0,1 \\[0, 4\\]")
                .pass("6 = 1,2 \\[1, 5\\]")
                .pass("6 = 2,0 \\[0, 2\\]")
                .pass("6 = 3,1 \\[1, 3\\]")
                .pass("6 = 4,2 \\[2, 4\\]")
                .pass("6 = 5,0 \\[3, 5\\]")
                .pass("6 = 6,1 \\[4\\]")
                .pass("6 = 0,2 \\[0, 5\\]")
                .pass("6 = 1,0 \\[0, 1\\]")
                .pass("6 = 2,1 \\[1, 2\\]")
                .pass("6 = 3,2 \\[2, 3\\]")
                .pass("6 = 4,0 \\[3, 4\\]")
                .pass("6 = 5,1 \\[4, 5\\]")
                .pass("6 = 6,2 \\[2\\]")
                .pass("6")
                .pass("ToListDefaultPairwise src-size=6",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=6")
                .pass("7 = 0,0 \\[0\\]")
                .pass("7 = 1,1 \\[1\\]")
                .pass("7 = 2,2 \\[2, 6\\]")
                .pass("7 = 3,3 \\[3\\]")
                .pass("7 = 4,0 \\[0, 4\\]")
                .pass("7 = 5,1 \\[1, 5\\]")
                .pass("7 = 6,2 \\[6\\]")
                .pass("7 = 0,3 \\[0, 3\\]")
                .pass("7 = 1,0 \\[0, 1\\]")
                .pass("7 = 2,1 \\[1, 2\\]")
                .pass("7 = 3,2 \\[2, 3\\]")
                .pass("7 = 4,3 \\[4\\]")
                .pass("7 = 5,0 \\[4, 5\\]")
                .pass("7 = 6,1 \\[5, 6\\]")
                .pass("7 = 0,2 \\[0, 6\\]")
                .pass("7 = 1,3 \\[1, 3\\]")
                .pass("7 = 2,0 \\[0, 2\\]")
                .pass("7 = 3,1 \\[3, 5\\]")
                .pass("7 = 4,2 \\[2, 4\\]")
                .pass("7 = 5,3 \\[5\\]")
                .pass("7 = 6,0 \\[4, 6\\]")
                .pass("7 = 0,1 \\[0, 5\\]")
                .pass("7 = 1,2 \\[1, 6\\]")
                .pass("7 = 2,3 \\[2\\]")
                .pass("7 = 3,0 \\[3, 4\\]")
                .pass("7 = 4,1 \\[1, 4\\]")
                .pass("7 = 5,2 \\[2, 5\\]")
                .pass("7 = 6,3 \\[3, 6\\]")
                .pass("7")
                .pass("ToListDefaultPairwise src-size=7",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=7")
                .pass("8 = 0,0 \\[0\\]")
                .pass("8 = 1,1 \\[1\\]")
                .pass("8 = 2,2 \\[2, 6\\]")
                .pass("8 = 3,3 \\[3, 7\\]")
                .pass("8 = 4,0 \\[0, 4\\]")
                .pass("8 = 5,1 \\[1, 5\\]")
                .pass("8 = 6,2 \\[6\\]")
                .pass("8 = 7,3 \\[7\\]")
                .pass("8 = 8,0 \\[4\\]")
                .pass("8 = 0,1 \\[0, 5\\]")
                .pass("8 = 1,2 \\[1, 6\\]")
                .pass("8 = 2,3 \\[2, 7\\]")
                .pass("8 = 3,0 \\[0, 3\\]")
                .pass("8 = 4,1 \\[1, 4\\]")
                .pass("8 = 5,2 \\[2, 5\\]")
                .pass("8 = 6,3 \\[3, 6\\]")
                .pass("8 = 7,0 \\[4, 7\\]")
                .pass("8 = 8,1 \\[5\\]")
                .pass("8 = 0,2 \\[0, 6\\]")
                .pass("8 = 1,3 \\[1, 7\\]")
                .pass("8 = 2,0 \\[0, 2\\]")
                .pass("8 = 3,1 \\[1, 3\\]")
                .pass("8 = 4,2 \\[2, 4\\]")
                .pass("8 = 5,3 \\[3, 5\\]")
                .pass("8 = 6,0 \\[4, 6\\]")
                .pass("8 = 7,1 \\[5, 7\\]")
                .pass("8 = 8,2 \\[2\\]")
                .pass("8 = 0,3 \\[0, 7\\]")
                .pass("8 = 1,0 \\[0, 1\\]")
                .pass("8 = 2,1 \\[1, 2\\]")
                .pass("8 = 3,2 \\[2, 3\\]")
                .pass("8 = 4,3 \\[3, 4\\]")
                .pass("8 = 5,0 \\[4, 5\\]")
                .pass("8 = 6,1 \\[5, 6\\]")
                .pass("8 = 7,2 \\[6, 7\\]")
                .pass("8 = 8,3 \\[3\\]")
                .pass("8")
                .pass("ToListDefaultPairwise src-size=8",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=8")
                .pass("9 = 0,0 \\[0\\]")
                .pass("9 = 1,1 \\[1\\]")
                .pass("9 = 2,2 \\[2, 7\\]")
                .pass("9 = 3,3 \\[3, 8\\]")
                .pass("9 = 4,4 \\[4\\]")
                .pass("9 = 5,0 \\[0, 5\\]")
                .pass("9 = 6,1 \\[1, 6\\]")
                .pass("9 = 7,2 \\[7\\]")
                .pass("9 = 8,3 \\[8\\]")
                .pass("9 = 0,4 \\[0, 4\\]")
                .pass("9 = 1,0 \\[0, 1\\]")
                .pass("9 = 2,1 \\[1, 2\\]")
                .pass("9 = 3,2 \\[2, 3\\]")
                .pass("9 = 4,3 \\[3, 4\\]")
                .pass("9 = 5,4 \\[5\\]")
                .pass("9 = 6,0 \\[5, 6\\]")
                .pass("9 = 7,1 \\[6, 7\\]")
                .pass("9 = 8,2 \\[7, 8\\]")
                .pass("9 = 0,3 \\[0, 8\\]")
                .pass("9 = 1,4 \\[1, 4\\]")
                .pass("9 = 2,0 \\[0, 2\\]")
                .pass("9 = 3,1 \\[1, 3\\]")
                .pass("9 = 4,2 \\[2, 4\\]")
                .pass("9 = 5,3 \\[3, 5\\]")
                .pass("9 = 6,4 \\[6\\]")
                .pass("9 = 7,0 \\[5, 7\\]")
                .pass("9 = 8,1 \\[6, 8\\]")
                .pass("9 = 0,2 \\[0, 7\\]")
                .pass("9 = 1,3 \\[1, 8\\]")
                .pass("9 = 2,4 \\[2\\]")
                .pass("9 = 3,0 \\[0, 3\\]")
                .pass("9 = 4,1 \\[4, 6\\]")
                .pass("9 = 5,2 \\[2, 5\\]")
                .pass("9 = 6,3 \\[3, 6\\]")
                .pass("9 = 7,4 \\[4, 7\\]")
                .pass("9 = 8,0 \\[5, 8\\]")
                .pass("9 = 0,1 \\[0, 6\\]")
                .pass("9 = 1,2 \\[1, 7\\]")
                .pass("9 = 2,3 \\[2, 8\\]")
                .pass("9 = 3,4 \\[3\\]")
                .pass("9 = 4,0 \\[4, 5\\]")
                .pass("9 = 5,1 \\[1, 5\\]")
                .pass("9 = 6,2 \\[2, 6\\]")
                .pass("9 = 7,3 \\[3, 7\\]")
                .pass("9 = 8,4 \\[4, 8\\]")
                .pass("9")
                .pass("ToListDefaultPairwise src-size=9",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=9");
    }

    @Test
    public void actualSeedsOnOneOrTwo() {
        expect
                .pass("0 1or2=\\[\\]")
                .pass("ToListDefaultPairwise src-size=0",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=0")
                .pass("1 1or2=\\[null\\]")
                .pass("ToListDefaultPairwise src-size=1",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=1")
                .pass("2 1or2=\\[null\\]")
                .pass("2 1or2=\\[null, b\\]")
                .pass("2 1or2=\\[b\\]")
                .pass("2")
                .pass("ToListDefaultPairwise src-size=2",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=2")
                .pass("3 1or2=\\[null\\]")
                .pass("3 1or2=\\[b\\]")
                .pass("3 1or2=\\[null, C\\]")
                .pass("3 1or2=\\[null, b\\]")
                .pass("3 1or2=\\[b, C\\]")
                .pass("3 1or2=\\[C\\]")
                .pass("3")
                .pass("ToListDefaultPairwise src-size=3",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=3")
                .pass("4 1or2=\\[null\\]")
                .pass("4 1or2=\\[b, 4\\]")
                .pass("4 1or2=\\[null, C\\]")
                .pass("4 1or2=\\[4\\]")
                .pass("4 1or2=\\[C\\]")
                .pass("4 1or2=\\[null, 4\\]")
                .pass("4 1or2=\\[null, b\\]")
                .pass("4 1or2=\\[b, C\\]")
                .pass("4 1or2=\\[C, 4\\]")
                .pass("4 1or2=\\[b\\]")
                .pass("4")
                .pass("ToListDefaultPairwise src-size=4",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=4")
                .pass("5 1or2=\\[null\\]")
                .pass("5 1or2=\\[b, 5\\]")
                .pass("5 1or2=\\[C\\]")
                .pass("5 1or2=\\[b, 4\\]")
                .pass("5 1or2=\\[C, 5\\]")
                .pass("5 1or2=\\[null, 5\\]")
                .pass("5 1or2=\\[null, b\\]")
                .pass("5 1or2=\\[C, 4\\]")
                .pass("5 1or2=\\[4\\]")
                .pass("5 1or2=\\[4, 5\\]")
                .pass("5 1or2=\\[null, C\\]")
                .pass("5 1or2=\\[b\\]")
                .pass("5 1or2=\\[b, C\\]")
                .pass("5 1or2=\\[null, 4\\]")
                .pass("5 1or2=\\[5\\]")
                .pass("5")
                .pass("ToListDefaultPairwise src-size=5",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=5")
                .pass("6 1or2=\\[null\\]")
                .pass("6 1or2=\\[b\\]")
                .pass("6 1or2=\\[C, 6\\]")
                .pass("6 1or2=\\[b, 4\\]")
                .pass("6 1or2=\\[C, 5\\]")
                .pass("6 1or2=\\[4, 6\\]")
                .pass("6 1or2=\\[5\\]")
                .pass("6 1or2=\\[null, 6\\]")
                .pass("6 1or2=\\[null, b\\]")
                .pass("6 1or2=\\[null, C\\]")
                .pass("6 1or2=\\[C, 4\\]")
                .pass("6 1or2=\\[b, 5\\]")
                .pass("6 1or2=\\[5, 6\\]")
                .pass("6 1or2=\\[4\\]")
                .pass("6 1or2=\\[null, 5\\]")
                .pass("6 1or2=\\[b, 6\\]")
                .pass("6 1or2=\\[b, C\\]")
                .pass("6 1or2=\\[null, 4\\]")
                .pass("6 1or2=\\[4, 5\\]")
                .pass("6 1or2=\\[6\\]")
                .pass("6 1or2=\\[C\\]")
                .pass("6")
                .pass("ToListDefaultPairwise src-size=6",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=6")
                .pass("7 1or2=\\[null\\]")
                .pass("7 1or2=\\[b\\]")
                .pass("7 1or2=\\[C, null\\]")
                .pass("7 1or2=\\[4\\]")
                .pass("7 1or2=\\[C, 5\\]")
                .pass("7 1or2=\\[6\\]")
                .pass("7 1or2=\\[6, null\\]")
                .pass("7 1or2=\\[null, 6\\]")
                .pass("7 1or2=\\[null, b\\]")
                .pass("7 1or2=\\[null, C\\]")
                .pass("7 1or2=\\[C, 4\\]")
                .pass("7 1or2=\\[5\\]")
                .pass("7 1or2=\\[5, 6\\]")
                .fail("7 1or2=\\[null\\]")
                        .withMessage(".*duplicate.*")
                .pass("7 1or2=\\[null, 4\\]")
                .pass("7 1or2=\\[b, null\\]")
                .pass("7 1or2=\\[b, C\\]")
                .pass("7 1or2=\\[4, 5\\]")
                .pass("7 1or2=\\[b, 5\\]")
                .pass("7 1or2=\\[b, 6\\]")
                .pass("7 1or2=\\[4, null\\]")
                .pass("7 1or2=\\[null, null\\]")
                .pass("7 1or2=\\[b, 4\\]")
                .pass("7 1or2=\\[C\\]")
                .pass("7 1or2=\\[4, 6\\]")
                .pass("7 1or2=\\[null, 5\\]")
                .pass("7 1or2=\\[C, 6\\]")
                .pass("7 1or2=\\[5, null\\]")
                .fail("7")
                        .withMessage(".*1.*fail.*total 28.*")
                .pass("ToListDefaultPairwise src-size=7",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=7")
                .pass("8 1or2=\\[null\\]")
                .pass("8 1or2=\\[b\\]")
                .pass("8 1or2=\\[C, null\\]")
                .pass("8 1or2=\\[4, HH\\]")
                .pass("8 1or2=\\[C, 5\\]")
                .pass("8 1or2=\\[4, 6\\]")
                .pass("8 1or2=\\[6, null\\]")
                .pass("8 1or2=\\[5, HH\\]")
                .pass("8 1or2=\\[C\\]")
                .pass("8 1or2=\\[null, 6\\]")
                .pass("8 1or2=\\[null, b\\]")
                .pass("8 1or2=\\[C, HH\\]")
                .pass("8 1or2=\\[null, 4\\]")
                .pass("8 1or2=\\[b, 5\\]")
                .pass("8 1or2=\\[C, 6\\]")
                .pass("8 1or2=\\[4, null\\]")
                .pass("8 1or2=\\[6, HH\\]")
                .pass("8 1or2=\\[5\\]")
                .pass("8 1or2=\\[null, null\\]")
                .pass("8 1or2=\\[b, HH\\]")
                .pass("8 1or2=\\[null, C\\]")
                .pass("8 1or2=\\[b, 4\\]")
                .pass("8 1or2=\\[4, 5\\]")
                .pass("8 1or2=\\[5, 6\\]")
                .fail("8 1or2=\\[null\\]")
                        .withMessage(".*duplicate.*")
                .pass("8 1or2=\\[null, HH\\]")
                .pass("8 1or2=\\[6\\]")
                .fail("8 1or2=\\[null, HH\\]")
                        .withMessage(".*duplicate.*")
                .pass("8 1or2=\\[b, null\\]")
                .pass("8 1or2=\\[b, C\\]")
                .pass("8 1or2=\\[C, 4\\]")
                .pass("8 1or2=\\[null, 5\\]")
                .pass("8 1or2=\\[b, 6\\]")
                .pass("8 1or2=\\[5, null\\]")
                .pass("8 1or2=\\[HH\\]")
                .pass("8 1or2=\\[4\\]")
                .fail("8")
                        .withMessage(".*2.*fail.*total 36.*")
                .pass("ToListDefaultPairwise src-size=8",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=8")
                .pass("9 1or2=\\[null\\]")
                .pass("9 1or2=\\[b\\]")
                .pass("9 1or2=\\[C, HH\\]")
                .pass("9 1or2=\\[4, !!\\]")
                .pass("9 1or2=\\[5\\]")
                .pass("9 1or2=\\[4, 6\\]")
                .fail("9 1or2=\\[null\\]")
                        .withMessage(".*duplicate.*")
                .pass("9 1or2=\\[HH\\]")
                .pass("9 1or2=\\[null, !!\\]")
                .pass("9 1or2=\\[null, null\\]")
                .pass("9 1or2=\\[null, b\\]")
                .pass("9 1or2=\\[null, C\\]")
                .pass("9 1or2=\\[C, 4\\]")
                .pass("9 1or2=\\[4, 5\\]")
                .pass("9 1or2=\\[6\\]")
                .pass("9 1or2=\\[6, null\\]")
                .pass("9 1or2=\\[null, HH\\]")
                .pass("9 1or2=\\[HH, !!\\]")
                .fail("9 1or2=\\[null, !!\\]")
                        .withMessage(".*duplicate.*")
                .pass("9 1or2=\\[b, 5\\]")
                .pass("9 1or2=\\[b, C\\]")
                .pass("9 1or2=\\[null, 4\\]")
                .pass("9 1or2=\\[C, 5\\]")
                .pass("9 1or2=\\[null, 6\\]")
                .pass("9 1or2=\\[4, null\\]")
                .pass("9 1or2=\\[5, HH\\]")
                .pass("9 1or2=\\[!!\\]")
                .fail("9 1or2=\\[null, HH\\]")
                        .withMessage(".*duplicate.*")
                .pass("9 1or2=\\[b, HH\\]")
                .pass("9 1or2=\\[C\\]")
                .pass("9 1or2=\\[b, 4\\]")
                .pass("9 1or2=\\[5, 6\\]")
                .pass("9 1or2=\\[b, 6\\]")
                .pass("9 1or2=\\[b, null\\]")
                .pass("9 1or2=\\[4, HH\\]")
                .pass("9 1or2=\\[5, !!\\]")
                .pass("9 1or2=\\[null, 5\\]")
                .pass("9 1or2=\\[b, !!\\]")
                .pass("9 1or2=\\[C, !!\\]")
                .pass("9 1or2=\\[4\\]")
                .pass("9 1or2=\\[5, null\\]")
                .pass("9 1or2=\\[C, 6\\]")
                .pass("9 1or2=\\[C, null\\]")
                .pass("9 1or2=\\[6, HH\\]")
                .pass("9 1or2=\\[6, !!\\]")
                .fail("9")
                        .withMessage(".*3.*fail.*total 45.*")
                .pass("ToListDefaultPairwise src-size=9",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=9");
    }

    @Test
    public void oneOrPermutationOfTwo() {
        expect
                .pass("0 1or2=\\[\\]")
                .pass("ToListDefaultPairwise src-size=0",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=0")
                .pass("1 1or2=\\[0\\]")
                .pass("ToListDefaultPairwise src-size=1",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=1")
                .pass("2 1or2=\\[0\\]")
                .pass("2 1or2=\\[0, 1\\]")
                .pass("2 1or2=\\[1\\]")
                .pass("2 1or2=\\[1, 0\\]")
                .pass("2")
                .pass("ToListDefaultPairwise src-size=2",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=2")
                .pass("3 1or2=\\[0\\]")
                .pass("3 1or2=\\[1\\]")
                .pass("3 1or2=\\[0, 2\\]")
                .pass("3 1or2=\\[2, 0\\]")
                .pass("3 1or2=\\[0, 1\\]")
                .pass("3 1or2=\\[1, 0\\]")
                .pass("3 1or2=\\[1, 2\\]")
                .pass("3 1or2=\\[2, 1\\]")
                .pass("3 1or2=\\[2\\]")
                .pass("3")
                .pass("ToListDefaultPairwise src-size=3",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=3")
                .pass("4 1or2=\\[0\\]")
                .pass("4 1or2=\\[1, 3\\]")
                .pass("4 1or2=\\[2, 1\\]")
                .pass("4 1or2=\\[2, 3\\]")
                .pass("4 1or2=\\[2\\]")
                .pass("4 1or2=\\[3, 2\\]")
                .pass("4 1or2=\\[1, 0\\]")
                .pass("4 1or2=\\[0, 2\\]")
                .pass("4 1or2=\\[0, 3\\]")
                .pass("4 1or2=\\[1\\]")
                .pass("4 1or2=\\[3, 0\\]")
                .pass("4 1or2=\\[3\\]")
                .pass("4")
                .pass("ToListDefaultPairwise src-size=4",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=4")
                .pass("5 1or2=\\[0\\]")
                .pass("5 1or2=\\[1, 4\\]")
                .pass("5 1or2=\\[2\\]")
                .pass("5 1or2=\\[3, 1\\]")
                .pass("5 1or2=\\[2, 4\\]")
                .pass("5 1or2=\\[4, 2\\]")
                .pass("5 1or2=\\[1, 0\\]")
                .pass("5 1or2=\\[0, 3\\]")
                .pass("5 1or2=\\[0, 4\\]")
                .pass("5 1or2=\\[2, 1\\]")
                .pass("5 1or2=\\[2, 0\\]")
                .pass("5 1or2=\\[2, 3\\]")
                .pass("5 1or2=\\[4, 3\\]")
                .pass("5 1or2=\\[1\\]")
                .pass("5 1or2=\\[3\\]")
                .pass("5 1or2=\\[4\\]")
                .pass("5")
                .pass("ToListDefaultPairwise src-size=5",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=5")
                .pass("6 1or2=\\[0\\]")
                .pass("6 1or2=\\[1\\]")
                .pass("6 1or2=\\[2, 5\\]")
                .pass("6 1or2=\\[3, 2\\]")
                .pass("6 1or2=\\[1, 4\\]")
                .pass("6 1or2=\\[5, 4\\]")
                .pass("6 1or2=\\[3\\]")
                .pass("6 1or2=\\[2, 0\\]")
                .pass("6 1or2=\\[0, 3\\]")
                .pass("6 1or2=\\[4, 2\\]")
                .pass("6 1or2=\\[5\\]")
                .pass("6 1or2=\\[0, 4\\]")
                .pass("6 1or2=\\[0, 1\\]")
                .pass("6 1or2=\\[4\\]")
                .pass("6 1or2=\\[5, 0\\]")
                .pass("6 1or2=\\[5, 1\\]")
                .pass("6 1or2=\\[3, 5\\]")
                .pass("6 1or2=\\[2, 1\\]")
                .pass("6 1or2=\\[1, 3\\]")
                .pass("6 1or2=\\[4, 3\\]")
                .pass("6 1or2=\\[2\\]")
                .pass("6")
                .pass("ToListDefaultPairwise src-size=6",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=6")
                .pass("7 1or2=\\[0\\]")
                .pass("7 1or2=\\[1\\]")
                .pass("7 1or2=\\[2, 6\\]")
                .pass("7 1or2=\\[3\\]")
                .pass("7 1or2=\\[4, 2\\]")
                .pass("7 1or2=\\[5\\]")
                .pass("7 1or2=\\[5, 6\\]")
                .pass("7 1or2=\\[6, 5\\]")
                .pass("7 1or2=\\[2, 0\\]")
                .pass("7 1or2=\\[0, 4\\]")
                .pass("7 1or2=\\[0, 6\\]")
                .pass("7 1or2=\\[3, 1\\]")
                .pass("7 1or2=\\[1, 3\\]")
                .pass("7 1or2=\\[5, 3\\]")
                .pass("7 1or2=\\[5, 2\\]")
                .pass("7 1or2=\\[5, 0\\]")
                .pass("7 1or2=\\[3, 4\\]")
                .pass("7 1or2=\\[4, 5\\]")
                .pass("7 1or2=\\[3, 6\\]")
                .pass("7 1or2=\\[1, 2\\]")
                .pass("7 1or2=\\[4\\]")
                .pass("7 1or2=\\[6, 1\\]")
                .pass("7 1or2=\\[6, 4\\]")
                .pass("7 1or2=\\[3, 0\\]")
                .pass("7 1or2=\\[2\\]")
                .pass("7 1or2=\\[2, 3\\]")
                .pass("7 1or2=\\[1, 4\\]")
                .pass("7 1or2=\\[5, 1\\]")
                .pass("7 1or2=\\[0, 1\\]")
                .pass("7 1or2=\\[6\\]")
                .pass("7")
                .pass("ToListDefaultPairwise src-size=7",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=7")
                .pass("8 1or2=\\[0\\]")
                .pass("8 1or2=\\[1\\]")
                .pass("8 1or2=\\[2, 6\\]")
                .pass("8 1or2=\\[3, 7\\]")
                .pass("8 1or2=\\[4, 2\\]")
                .pass("8 1or2=\\[5, 3\\]")
                .pass("8 1or2=\\[5, 6\\]")
                .pass("8 1or2=\\[7, 5\\]")
                .pass("8 1or2=\\[4\\]")
                .pass("8 1or2=\\[7, 2\\]")
                .pass("8 1or2=\\[3, 2\\]")
                .pass("8 1or2=\\[0, 4\\]")
                .pass("8 1or2=\\[4, 5\\]")
                .pass("8 1or2=\\[6, 4\\]")
                .pass("8 1or2=\\[6, 7\\]")
                .pass("8 1or2=\\[0, 5\\]")
                .pass("8 1or2=\\[7, 1\\]")
                .pass("8 1or2=\\[5\\]")
                .pass("8 1or2=\\[7, 0\\]")
                .pass("8 1or2=\\[1, 6\\]")
                .pass("8 1or2=\\[2, 0\\]")
                .pass("8 1or2=\\[3, 1\\]")
                .pass("8 1or2=\\[3, 4\\]")
                .pass("8 1or2=\\[5, 2\\]")
                .pass("8 1or2=\\[6\\]")
                .pass("8 1or2=\\[4, 7\\]")
                .pass("8 1or2=\\[3\\]")
                .pass("8 1or2=\\[0, 6\\]")
                .pass("8 1or2=\\[1, 0\\]")
                .pass("8 1or2=\\[1, 2\\]")
                .pass("8 1or2=\\[0, 3\\]")
                .pass("8 1or2=\\[4, 1\\]")
                .pass("8 1or2=\\[1, 5\\]")
                .pass("8 1or2=\\[3, 6\\]")
                .pass("8 1or2=\\[7\\]")
                .pass("8 1or2=\\[2\\]")
                .pass("8")
                .pass("ToListDefaultPairwise src-size=8",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=8")
                .pass("9 1or2=\\[0\\]")
                .pass("9 1or2=\\[1\\]")
                .pass("9 1or2=\\[2, 7\\]")
                .pass("9 1or2=\\[3, 8\\]")
                .pass("9 1or2=\\[4\\]")
                .pass("9 1or2=\\[5, 2\\]")
                .pass("9 1or2=\\[6, 3\\]")
                .pass("9 1or2=\\[4, 7\\]")
                .pass("9 1or2=\\[8, 4\\]")
                .pass("9 1or2=\\[2, 0\\]")
                .pass("9 1or2=\\[0, 3\\]")
                .pass("9 1or2=\\[1, 5\\]")
                .pass("9 1or2=\\[6, 1\\]")
                .pass("9 1or2=\\[7, 3\\]")
                .pass("9 1or2=\\[7, 8\\]")
                .pass("9 1or2=\\[0, 8\\]")
                .pass("9 1or2=\\[1, 0\\]")
                .pass("9 1or2=\\[4, 6\\]")
                .pass("9 1or2=\\[7, 0\\]")
                .pass("9 1or2=\\[1, 4\\]")
                .pass("9 1or2=\\[3, 1\\]")
                .pass("9 1or2=\\[4, 3\\]")
                .pass("9 1or2=\\[5, 6\\]")
                .pass("9 1or2=\\[2\\]")
                .pass("9 1or2=\\[0, 5\\]")
                .pass("9 1or2=\\[7\\]")
                .pass("9 1or2=\\[8, 6\\]")
                .pass("9 1or2=\\[4, 0\\]")
                .pass("9 1or2=\\[1, 7\\]")
                .pass("9 1or2=\\[2, 8\\]")
                .pass("9 1or2=\\[3, 2\\]")
                .pass("9 1or2=\\[5, 4\\]")
                .pass("9 1or2=\\[5, 3\\]")
                .pass("9 1or2=\\[6\\]")
                .pass("9 1or2=\\[6, 7\\]")
                .pass("9 1or2=\\[5, 8\\]")
                .pass("9 1or2=\\[0, 6\\]")
                .pass("9 1or2=\\[8, 1\\]")
                .pass("9 1or2=\\[2, 1\\]")
                .pass("9 1or2=\\[3\\]")
                .pass("9 1or2=\\[2, 4\\]")
                .pass("9 1or2=\\[5\\]")
                .pass("9 1or2=\\[2, 6\\]")
                .pass("9 1or2=\\[7, 5\\]")
                .pass("9 1or2=\\[8\\]")
                .pass("9")
                .pass("ToListDefaultPairwise src-size=9",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=9");
    }

    @Test
    public void individuallyCombined() {
        expect
                .pass("0 all=\\{size=0\\}\\[\\]")
                .pass("ToListDefaultPairwise src-size=0",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=0")
                .pass("1 all=\\{size=0\\}\\[\\]")
                .pass("1 all=\\{size=1\\}\\[11\\]")
                .pass("1")
                .pass("ToListDefaultPairwise src-size=1",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=1")
                .pass("2 all=\\{size=0\\}\\[\\]")
                .pass("2 all=\\{size=2\\}\\[11, 12\\]")
                .pass("2 all=\\{size=1\\}\\[12\\]")
                .pass("2 all=\\{size=1\\}\\[11\\]")
                .pass("2")
                .pass("ToListDefaultPairwise src-size=2",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=2")
                .pass("3 all=\\{size=0\\}\\[\\]")
                .pass("3 all=\\{size=2\\}\\[11, 12\\]")
                .pass("3 all=\\{size=2\\}\\[12, 13\\]")
                .pass("3 all=\\{size=2\\}\\[11, 13\\]")
//                .pass("3 all=\\{size=1\\}\\[13\\]")
//                .pass("3 all=\\{size=2\\}\\[11, 12\\]")
                .pass("3")
                .pass("ToListDefaultPairwise src-size=3",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=3")
                .pass("4 all=\\{size=0\\}\\[\\]")
                .pass("4 all=\\{size=3\\}\\[11, 12, 14\\]")
                .pass("4 all=\\{size=2\\}\\[12, 13\\]")
                .pass("4 all=\\{size=3\\}\\[11, 13, 14\\]")
                .pass("4 all=\\{size=1\\}\\[14\\]")
                .pass("4 all=\\{size=3\\}\\[11, 12, 13\\]")
                .pass("4")
                .pass("ToListDefaultPairwise src-size=4",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=4")
                .pass("5 all=\\{size=0\\}\\[\\]")
                .pass("5 all=\\{size=4\\}\\[11, 12, 14, 15\\]")
                .pass("5 all=\\{size=3\\}\\[12, 13, 15\\]")
                .pass("5 all=\\{size=3\\}\\[11, 13, 14\\]")
                .pass("5 all=\\{size=2\\}\\[14, 15\\]")
                .pass("5 all=\\{size=3\\}\\[11, 12, 13\\]")
//                .pass("5 all=\\{size=3\\}\\[12, 13, 15\\]")
//                .pass("5 all=\\{size=2\\}\\[11, 14\\]")
                .pass("5")
                .pass("ToListDefaultPairwise src-size=5",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=5")
                .pass("6 all=\\{size=0\\}\\[\\]")
                .pass("6 all=\\{size=5\\}\\[11, 12, 14, 15, 16\\]")
                .pass("6 all=\\{size=4\\}\\[12, 13, 15, 16\\]")
                .pass("6 all=\\{size=3\\}\\[11, 13, 14\\]")
                .pass("6 all=\\{size=3\\}\\[14, 15, 16\\]")
                .pass("6 all=\\{size=3\\}\\[11, 12, 13\\]")
                .pass("6 all=\\{size=3\\}\\[12, 14, 16\\]")
                .pass("6 all=\\{size=3\\}\\[11, 13, 15\\]")
                .pass("6")
                .pass("ToListDefaultPairwise src-size=6",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=6")
                .pass("7 all=\\{size=0\\}\\[\\]")
                .pass("7 all=\\{size=5\\}\\[11, 12, 14, 15, 16\\]")
                .pass("7 all=\\{size=5\\}\\[12, 13, 15, 16, 17\\]")
                .pass("7 all=\\{size=4\\}\\[11, 13, 14, 17\\]")
                .pass("7 all=\\{size=4\\}\\[14, 15, 16, 17\\]")
                .pass("7 all=\\{size=3\\}\\[11, 12, 13\\]")
                .pass("7 all=\\{size=3\\}\\[12, 14, 16\\]")
                .pass("7 all=\\{size=4\\}\\[11, 13, 15, 17\\]")
                .pass("7")
                .pass("ToListDefaultPairwise src-size=7",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=7")
                .pass("8 all=\\{size=0\\}\\[\\]")
                .pass("8 all=\\{size=6\\}\\[11, 12, 14, 15, 16, 18\\]")
                .pass("8 all=\\{size=5\\}\\[12, 13, 15, 16, 17\\]")
                .pass("8 all=\\{size=5\\}\\[11, 13, 14, 17, 18\\]")
                .pass("8 all=\\{size=4\\}\\[14, 15, 16, 17\\]")
                .pass("8 all=\\{size=4\\}\\[11, 12, 13, 18\\]")
                .pass("8 all=\\{size=5\\}\\[12, 14, 16, 17, 18\\]")
                .pass("8 all=\\{size=3\\}\\[11, 13, 15\\]")
                .pass("8")
                .pass("ToListDefaultPairwise src-size=8",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=8")
                .pass("9 all=\\{size=0\\}\\[\\]")
                .pass("9 all=\\{size=7\\}\\[11, 12, 14, 15, 16, 18, 19\\]")
                .pass("9 all=\\{size=5\\}\\[12, 13, 15, 16, 17\\]")
                .pass("9 all=\\{size=6\\}\\[11, 13, 14, 17, 18, 19\\]")
                .pass("9 all=\\{size=5\\}\\[14, 15, 16, 17, 19\\]")
                .pass("9 all=\\{size=4\\}\\[11, 12, 13, 18\\]")
                .pass("9 all=\\{size=5\\}\\[12, 14, 16, 17, 18\\]")
                .pass("9 all=\\{size=4\\}\\[11, 13, 15, 19\\]")
//                .pass("9 all=\\{size=4\\}\\[15, 16, 17, 18\\]")
//                .pass("9 all=\\{size=5\\}\\[11, 12, 13, 14, 19\\]")
                .pass("9")
                .pass("ToListDefaultPairwise src-size=9",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=9");
    }

    @Test
    public void permutations() {
        expect
                .fail(" src-size=0 / 0\\.\\d{3}s")
                .pass("ToListDefaultPairwise src-size=0",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=0")
                .pass("1 permutation=\\[z\\]")
                .pass("ToListDefaultPairwise src-size=1",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=1")
                .pass("2 permutation=\\[z, Y\\]")
                .pass("2 permutation=\\[Y, z\\]")
                .pass("2")
                .pass("ToListDefaultPairwise src-size=2",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=2")
                .pass("3 permutation=\\[z, Y, x\\]")
                .pass("3 permutation=\\[x, z, Y\\]")
                .pass("3 permutation=\\[Y, x, z\\]")
                .pass("3 permutation=\\[z, x, Y\\]")
                .pass("3 permutation=\\[Y, z, x\\]")
                .pass("3 permutation=\\[x, Y, z\\]")
                .pass("3")
                .pass("ToListDefaultPairwise src-size=3",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=3")
                .pass("4 permutation=\\[z, Y, x, 9\\]")
                .pass("4 permutation=\\[x, z, Y, 9\\]")
                .pass("4 permutation=\\[9, x, z, Y\\]")
                .pass("4 permutation=\\[9, Y, x, z\\]")
                .pass("4 permutation=\\[z, 9, x, Y\\]")
                .pass("4 permutation=\\[Y, x, z, 9\\]")
                .pass("4 permutation=\\[Y, z, 9, x\\]")
                .pass("4 permutation=\\[x, 9, Y, z\\]")
                .pass("4 permutation=\\[z, x, Y, 9\\]")
                .pass("4 permutation=\\[x, z, 9, Y\\]")
                .pass("4 permutation=\\[9, Y, z, x\\]")
                .pass("4 permutation=\\[Y, 9, x, z\\]")
                .pass("4")
                .pass("ToListDefaultPairwise src-size=4",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=4")
                .pass("5 permutation=\\[z, Y, x, 9, 8\\]")
                .pass("5 permutation=\\[x, z, Y, 8, 9\\]")
                .pass("5 permutation=\\[9, x, 8, z, Y\\]")
                .pass("5 permutation=\\[9, 8, x, Y, z\\]")
                .pass("5 permutation=\\[8, z, 9, Y, x\\]")
                .pass("5 permutation=\\[Y, 8, z, x, 9\\]")
                .pass("5 permutation=\\[8, Y, x, z, 9\\]")
                .pass("5 permutation=\\[9, x, Y, 8, z\\]")
                .pass("5 permutation=\\[x, Y, 8, 9, z\\]")
                .pass("5 permutation=\\[9, z, x, Y, 8\\]")
                .pass("5 permutation=\\[z, Y, 9, 8, x\\]")
                .pass("5 permutation=\\[9, 8, Y, z, x\\]")
                .pass("5 permutation=\\[8, x, 9, Y, z\\]")
                .pass("5 permutation=\\[z, x, 8, Y, 9\\]")
                .pass("5 permutation=\\[9, z, Y, x, 8\\]")
                .pass("5 permutation=\\[Y, x, z, 9, 8\\]")
                .pass("5 permutation=\\[z, Y, 8, 9, x\\]")
                .pass("5 permutation=\\[8, x, z, Y, 9\\]")
                .pass("5 permutation=\\[Y, 9, x, z, 8\\]")
                .pass("5 permutation=\\[z, 8, x, 9, Y\\]")
                .pass("5 permutation=\\[x, 9, z, 8, Y\\]")
                .pass("5 permutation=\\[Y, z, 8, 9, x\\]")
                .pass("5")
                .pass("ToListDefaultPairwise src-size=5",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=5")
                .pass("6 permutation=\\[z, Y, x, 9, 8, 7\\]")
                .pass("6 permutation=\\[x, 7, z, Y, 8, 9\\]")
                .pass("6 permutation=\\[9, x, 7, 8, z, Y\\]")
                .pass("6 permutation=\\[9, 8, x, 7, Y, z\\]")
                .pass("6 permutation=\\[7, 8, z, 9, Y, x\\]")
                .pass("6 permutation=\\[7, Y, 8, z, x, 9\\]")
                .pass("6 permutation=\\[Y, 9, z, 8, 7, x\\]")
                .pass("6 permutation=\\[8, x, 9, Y, 7, z\\]")
                .pass("6 permutation=\\[9, z, Y, x, 8, 7\\]")
                .pass("6 permutation=\\[7, x, Y, 8, z, 9\\]")
                .pass("6 permutation=\\[Y, 7, 9, x, z, 8\\]")
                .pass("6 permutation=\\[z, x, 9, 8, Y, 7\\]")
                .pass("6 permutation=\\[Y, 8, 7, x, 9, z\\]")
                .pass("6 permutation=\\[z, 7, Y, 8, 9, x\\]")
                .pass("6 permutation=\\[8, 9, z, x, Y, 7\\]")
                .pass("6 permutation=\\[Y, 8, x, z, 7, 9\\]")
                .pass("6 permutation=\\[x, Y, 9, 7, 8, z\\]")
                .pass("6 permutation=\\[7, 9, Y, z, x, 8\\]")
                .pass("6 permutation=\\[z, 7, 8, x, 9, Y\\]")
                .pass("6 permutation=\\[7, 9, z, 8, x, Y\\]")
                .pass("6 permutation=\\[8, x, 9, z, Y, 7\\]")
                .pass("6 permutation=\\[9, Y, 7, 8, x, z\\]")
                .pass("6 permutation=\\[z, 8, 9, Y, 7, x\\]")
                .pass("6 permutation=\\[8, Y, z, 7, x, 9\\]")
                .pass("6 permutation=\\[7, z, x, 9, Y, 8\\]")
                .pass("6")
                .pass("ToListDefaultPairwise src-size=6",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=6")
                .pass("7 permutation=\\[z, Y, x, 9, 8, 7, W\\]")
                .pass("7 permutation=\\[x, 7, z, Y, 8, W, 9\\]")
                .pass("7 permutation=\\[9, x, 7, 8, W, z, Y\\]")
                .pass("7 permutation=\\[9, 8, x, W, 7, Y, z\\]")
                .pass("7 permutation=\\[8, z, W, 9, Y, 7, x\\]")
                .pass("7 permutation=\\[7, W, Y, 8, z, x, 9\\]")
                .pass("7 permutation=\\[W, 7, 8, x, Y, z, 9\\]")
                .pass("7 permutation=\\[W, Y, 9, x, 8, 7, z\\]")
                .pass("7 permutation=\\[x, W, 9, 8, Y, 7, z\\]")
                .pass("7 permutation=\\[9, W, z, 7, Y, x, 8\\]")
                .pass("7 permutation=\\[z, x, 9, 7, W, 8, Y\\]")
                .pass("7 permutation=\\[Y, 7, 9, W, z, x, 8\\]")
                .pass("7 permutation=\\[x, 8, W, Y, 9, z, 7\\]")
                .pass("7 permutation=\\[8, 9, 7, z, x, W, Y\\]")
                .pass("7 permutation=\\[Y, x, 8, 7, 9, W, z\\]")
                .pass("7 permutation=\\[z, 8, Y, 9, 7, x, W\\]")
                .pass("7 permutation=\\[x, Y, 7, W, z, 8, 9\\]")
                .pass("7 permutation=\\[9, Y, x, 7, W, z, 8\\]")
                .pass("7 permutation=\\[W, z, x, 8, 9, Y, 7\\]")
                .pass("7 permutation=\\[7, Y, W, z, 8, 9, x\\]")
                .pass("7 permutation=\\[x, 7, 8, 9, W, z, Y\\]")
                .pass("7 permutation=\\[8, Y, x, 9, W, z, 7\\]")
                .pass("7 permutation=\\[z, 9, 8, Y, 7, x, W\\]")
                .pass("7 permutation=\\[x, 7, z, 9, Y, 8, W\\]")
                .pass("7")
                .pass("ToListDefaultPairwise src-size=7",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=7")
                .pass("8 permutation=\\[z, Y, x, 9, 8, 7, W, v\\]")
                .pass("8 permutation=\\[x, 7, z, Y, 8, W, v, 9\\]")
                .pass("8 permutation=\\[9, x, 7, 8, W, v, z, Y\\]")
                .pass("8 permutation=\\[9, 8, x, W, v, 7, Y, z\\]")
                .pass("8 permutation=\\[8, Y, W, v, z, 9, 7, x\\]")
                .pass("8 permutation=\\[7, W, v, z, 8, x, Y, 9\\]")
                .pass("8 permutation=\\[W, v, 8, x, Y, 7, z, 9\\]")
                .pass("8 permutation=\\[v, W, Y, 9, 7, x, 8, z\\]")
                .pass("8 permutation=\\[v, z, W, x, 8, 9, 7, Y\\]")
                .pass("8 permutation=\\[7, 9, z, Y, x, 8, W, v\\]")
                .pass("8 permutation=\\[8, Y, 7, W, v, x, 9, z\\]")
                .pass("8 permutation=\\[Y, v, 7, W, 8, x, z, 9\\]")
                .pass("8 permutation=\\[x, 9, Y, 7, W, v, 8, z\\]")
                .pass("8 permutation=\\[x, z, v, 8, 9, Y, W, 7\\]")
                .pass("8 permutation=\\[7, x, W, v, Y, 8, 9, z\\]")
                .pass("8 permutation=\\[z, 8, Y, 9, x, W, v, 7\\]")
                .pass("8 permutation=\\[z, 7, v, Y, 9, W, x, 8\\]")
                .pass("8 permutation=\\[9, x, z, W, v, Y, 7, 8\\]")
                .pass("8 permutation=\\[z, v, W, Y, 9, 7, 8, x\\]")
                .pass("8 permutation=\\[W, 9, Y, x, z, v, 7, 8\\]")
                .pass("8 permutation=\\[8, v, W, x, 7, z, 9, Y\\]")
                .pass("8 permutation=\\[9, Y, W, v, z, 8, x, 7\\]")
                .pass("8 permutation=\\[v, Y, 8, z, 7, W, 9, x\\]")
                .pass("8 permutation=\\[7, 8, z, Y, x, v, W, 9\\]")
                .pass("8 permutation=\\[7, Y, x, 8, z, 9, v, W\\]")
                .pass("8")
                .pass("ToListDefaultPairwise src-size=8",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=8")
                .pass("9 permutation=\\[z, Y, x, 9, 8, 7, W, v, !\\]")
                .pass("9 permutation=\\[x, z, Y, 8, 7, W, v, !, 9\\]")
                .pass("9 permutation=\\[9, x, 8, 7, W, v, !, z, Y\\]")
                .pass("9 permutation=\\[9, 8, 7, W, v, !, x, Y, z\\]")
                .pass("9 permutation=\\[8, 7, W, v, !, z, 9, Y, x\\]")
                .pass("9 permutation=\\[7, W, v, !, Y, 8, z, x, 9\\]")
                .pass("9 permutation=\\[W, v, !, 8, Y, 7, x, z, 9\\]")
                .pass("9 permutation=\\[v, !, 9, W, x, Y, 8, z, 7\\]")
                .pass("9 permutation=\\[!, v, x, 7, Y, W, 8, 9, z\\]")
                .pass("9 permutation=\\[!, W, v, 7, 9, z, x, Y, 8\\]")
                .pass("9 permutation=\\[z, Y, !, v, 8, 9, 7, W, x\\]")
                .pass("9 permutation=\\[x, !, 8, W, v, Y, 7, z, 9\\]")
                .pass("9 permutation=\\[8, 9, z, !, Y, v, W, x, 7\\]")
                .pass("9 permutation=\\[x, 7, 9, z, v, !, 8, Y, W\\]")
                .pass("9 permutation=\\[z, x, 7, Y, W, v, !, 9, 8\\]")
                .pass("9 permutation=\\[Y, x, 9, 7, !, z, W, v, 8\\]")
                .pass("9 permutation=\\[7, z, x, W, 9, 8, Y, v, !\\]")
                .pass("9 permutation=\\[Y, 8, 9, z, 7, x, W, v, !\\]")
                .pass("9 permutation=\\[Y, 7, W, z, 8, 9, v, !, x\\]")
                .pass("9 permutation=\\[7, 8, x, 9, z, W, v, !, Y\\]")
                .pass("9 permutation=\\[7, 9, Y, v, 8, !, x, z, W\\]")
                .pass("9 permutation=\\[x, W, z, 7, !, 8, 9, Y, v\\]")
                .pass("9 permutation=\\[v, W, z, !, 8, 9, x, 7, Y\\]")
                .pass("9 permutation=\\[8, Y, x, W, 9, v, !, 7, z\\]")
                .pass("9 permutation=\\[!, Y, 9, v, z, W, x, 8, 7\\]")
                .pass("9 permutation=\\[!, W, v, z, Y, 9, 7, 8, x\\]")
                .pass("9 permutation=\\[9, v, !, W, 7, z, Y, x, 8\\]")
                .pass("9 permutation=\\[x, 8, !, z, 9, Y, v, W, 7\\]")
                .pass("9 permutation=\\[v, Y, z, x, 7, !, 8, 9, W\\]")
                .pass("9 permutation=\\[9, Y, v, !, W, 7, x, 8, z\\]")
                .pass("9 permutation=\\[z, 7, 8, x, W, Y, !, v, 9\\]")
                .pass("9 permutation=\\[9, !, Y, W, z, v, x, 7, 8\\]")
                .pass("9 permutation=\\[8, W, v, x, 9, 7, Y, z, !\\]")
                .pass("9 permutation=\\[W, z, 9, v, 8, x, Y, !, 7\\]")
                .pass("9")
                .pass("ToListDefaultPairwise src-size=9",
                        "org.lazyparams.showcase.ToListDefaultPairwise src-size=9");
    }
}
